### ISSUE TITLE
Break the repo into two code samples, one Rust one Typescript, and add Typescript code and documentation

### ISSUE THREAD

**Issue by Connoropolous** [holochain/happ-client-call-tutorial#1]

**Comment by jost-s** [comment]
@Connoropolous I want to do this 🙂 I'll write the TS code and documentation. How do you want the repo to be structured? Separate folders for Rust and TS examples?

**Comment by Connoropolous** [comment]
oh wonderful! yes, separate folders. 

Just make sure to use a historical version of holochain-conductor-api if you need to, that matches the version this is running at.

**Comment by Connoropolous** [comment]
closed by #2
